### ISSUE TITLE
Can't use dotenvy inside Livebook (with Mix.install)?

### ISSUE THREAD

**Issue by georgeguimaraes** [fireproofsocks/dotenvy#25]
A project that uses dotenvy makes it unable to be used by Livebook and Mix.install's config_path. 

So, I want to use Livebook as a documentation / REPL tool for a project. I'm following the example at https://hexdocs.pm/livebook/use_cases.html#documentation-with-mix-install .

Using Mix.install, we can use `config_path: :my_app` to load `runtime.exs`. However, this does not work with a project that uses dotenvy.

I guess it is because dotenvy uses Process dictionary, which may not make sense inside Livebook.

**Comment by lud** [comment]
In my company we have this hack:

```elixlir
import Dotenvy

put_all_vars = fn vars ->
  Process.put(:dotenvy_vars, vars)
  System.put_env(vars)
end

 source!([".env", System.get_env(), ".env.override"], side_effect: put_all_vars)
 ```
 
 For my personal projects I just made a [fork](https://github.com/lud/nvir) that works just the way I think it should.

**Comment by georgeguimaraes** [comment]
@lud interesting, tks for the hack!

**Comment by fireproofsocks** [comment]
Interesting.  What's the error that happens if you try to use `dotenvy` from inside a livebook?

**Comment by georgeguimaraes** [comment]
Using this in my livebook:

```elixir
Mix.install(
  [
    {:specialist, path: "~/code/specialist", env: :dev}
  ],
  config_path: :specialist,
  lockfile: :specialist
)
```

after it compiles, I get this error:

```
** (RuntimeError) Dotenv variable DATABASE_URL not set
    (dotenvy 0.9.0) lib/dotenvy.ex:153: Dotenvy.env!/2
    /Users/george/code/specialist/config/runtime.exs:31: (file)
```

DATABASE_URL is indeed set in my .env.dev.

And my runtime.exs: 
```elixir
Dotenvy.source!([
  System.get_env(),
  ".env.#{config_env()}",
  ".env.#{config_env()}.local",
  System.get_env()
])
```

Unfortunately, @lud hack hasn't worked for me.

**Comment by fireproofsocks** [comment]
Hmm... I'm not able to reproduce this (although I admit I am not very familiar with livebooks).  The only error I encountered was because of the path.  To test this, I created a simple app `foo` that uses `dotenvy` as a package.  Inside its `runtime.exs` I have something like this:

```
import Config
import Dotenvy

source!(["/path/to/foo/.env", System.get_env()])
# a relative path won't work!
# source!([".env", System.get_env()])

config :foo, :secret, env!("SECRET", :string!)
```

and I have a `.env` file in that repo:

```
SECRET=my-secret
```

I can test this by running the `foo` app:

```
iex> Application.get_env(:foo, :secret)
"my-secret"
```

I can include this in a livebook using your example:
```
Mix.install(
  [
    {:foo, path: "/path/to/foo", env: :dev}
  ],
  config_path: :foo,
  lockfile: :foo
)
```

And I can evaluate a cell the same way as before:
```
Application.get_env(:foo, :secret)
```
and it does read the environment variable. 

This ONLY works if I use the full path to the `.env` file.  If the `runtime.exs` in my `foo` app only specifies `.env` without the full path, then that triggers an error because the relative path is different when you are executing the code from livebook vs. when you are executing it from inside the app's root directory:

```
** (RuntimeError) Dotenv variable SECRET not set
    (dotenvy 0.9.0) lib/dotenvy.ex:153: Dotenvy.env!/2
```

This does make sense: relative paths get weird when your point of entry changes.  I remember this exact thing happening with python apps when they were embedded in Jupyter notebooks, for example.  

There are some similar hoops to jump through with paths when dealing with releases -- see https://hexdocs.pm/dotenvy/strategies.html#releases 
I'm fairly confident you can put something together (e.g. using `__DIR__`) that would resolve the ambiguity of the relative path when running an app via a livebook.

**Comment by fireproofsocks** [comment]
Actually, the more succinct example from the Strategies page works fine:

```
env_dir_prefix = System.get_env("RELEASE_ROOT") || Path.expand("./envs/") <> "/"

source!([
  "#{env_dir_prefix}.env",
  "#{env_dir_prefix}.#{config_env()}.env",
  "#{env_dir_prefix}.#{config_env()}.overrides.env",
  System.get_env()
])
```

As long as you have `Path.expand/1` in your app, it will result in a fully qualified path to your `.env` files, and this should avoid any errors.

I will update the docs to include an explicit example for livebooks.
